Pdf contract exporten en uploaden
Gieljermo/Bazaar pull request #5
Opened 2024-02-25 12:47 UTC by Thampie2185577

2024-02-26 10:52 UTC, Gieljermo requested changes
Ik denk dat het beter is als het contract goedgekeurd kan worden door de gebruiker.
hoe het nu is upload de admin het ocntract en upload hem zelf. Dus de gebruiker heeft deze al odnertekend door te registreeren denk ik.

Als de admin het dan heeft ondertekend dan upload hij het naar de gebruiker en kan de gebruiker het goedkeuren. Ik kan als gebruiker nu nergens het odnertekende contract zien en goedkeuren.

2024-02-26 10:52 UTC, Gieljermo commented on app/Http/Controllers/AdminController.php
> +            $users = User::whereRaw('role_id = ?', $role_id)->get();
Waarom hier whereRaw en eerst role_id = ' ?'' ?

2024-02-26 10:52 UTC, Gieljermo commented on app/Http/Controllers/AdminController.php
> +            $contract->file = $fileData;
Ik zie dat er een file in de database word gezet? Hoe kan deze gelezen worden

2024-02-26 10:52 UTC, Gieljermo commented on app/Http/Controllers/UserController.php
> +    public function update(Request $request, $id)
Waarom hier naar id veranderd en bij de edit method niet. Ik denk dat we beter consistent kunne blijven met of we dit wel of niet doen.

2024-02-26 10:52 UTC, Gieljermo commented on resources/views/admin/contract.blade.php
Liever geen css in de views. Doe in de css of scss

2024-02-26 10:52 UTC, Gieljermo commented on routes/web.php
> +});
Ik zou dit even op 1 lijn zetten. Ziet er netter uit

2024-02-26 10:54 UTC, Thampie2185577 commented on app/Http/Controllers/AdminController.php
> +            $users = User::whereRaw('role_id = ?', $role_id)->get();
het was bedoelt voor sql injection

2024-02-26 11:21 UTC, Thampie2185577 commented on resources/views/admin/contract.blade.php
ik heb dit geprobeerd, Jammer genoeg werkt dan het exporteren van de pdf niet, omdat stylesheet in andere bestand staat waardoor heel lang duurt om de bestand van te maken. Ik denk dat het verstandiger is om alleen voor deze bestand de style in de view te laten zitten.

2024-02-26 12:11 UTC, Gieljermo commented on resources/views/admin/contract.blade.php
Okee dan is het goed

2024-02-26 13:41 UTC, Gieljermo requested changes
Ziet er stuk beter uit.

Is het mogelijk om een soort melding te maken bijv. Je contract is geupload accepteer hem hier.(dit is even een voorbeeld.) En dat ze hem dan kunnen dowloaden en ook kunnen accepteren. Ziet er wat mooier uit dan zo vol in je scherm naar mijn mening. 

Als dit te veel moeite is is dit ook prima. 

Daarnaast lijkt het mij niet nodig om voor elke soort user een verschillende homapge te hebben. Ze hebben natuurlijk wel andere rechten. Homepage lijkt mij handiog als dat voor iedereen de advertenties zijn of een soort homepage met een aantal uitgelichte advertenties

2024-02-28 08:59 UTC, Gieljermo requested changes
Werking is goed. Ik zie alleen in de web routes nog steeds dat er verschillende indexes zijn voor de verschillende types gebruiekrs. We hadden nu toch afgesproken dit niet te doen?

Haal deze dan ook weg. Ook worden de user nog niet naar de standaard index van de website gestuurd maar naar een apparte index getuurd.

2024-02-28 12:22 UTC, Gieljermo approved these changes

2024-02-28 12:23 UTC, merged